name: Publish releases

on:
  push:
    branches: [main]

env:
  YARN_ENABLE_GLOBAL_CACHE: false

permissions:
  contents: read

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created:  ${{ steps.release.outputs.release_created }}
      release_tag:  ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@db8f2c60ee802b3748b512940dde88eabd7b7e01  # v3.7.13
        id: release
        with:
          release-type: node
          package-name: corepack
          bump-minor-pre-major: true # TODO: remove this when releasing v1.0.0.

  npm-publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444  # v5.0.0
        with:
          node-version: lts/*
        env:
          SKIP_YARN_COREPACK_CHECK: 1

      - name: Get the Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(corepack yarn config get cacheFolder)" >> "$GITHUB_OUTPUT"

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830  # v4.3.0
        with:
          path: ${{steps.yarn-cache-dir-path.outputs.dir}}
          key: ${{runner.os}}-yarn-${{hashFiles('**/yarn.lock')}}
          restore-keys: |
            ${{runner.os}}-yarn-

      - run: corepack yarn install --immutable

      - name: Publish to the npm registry
        run: corepack yarn npm publish --provenance

      - run: corepack yarn pack --out corepack.tgz
      - name: Add Corepack package archive to GitHub release
        run: gh release upload ${{ needs.release-please.outputs.release_tag }} corepack.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
